# Generated by Django 5.2.7 on 2025-10-20 16:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="esta_activo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="curso",
            name="fecha_creado",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="curso",
            name="nombre",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="fecha_actualizado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="fecha_creado",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="plan",
            name="nombre",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="precio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="se_renueva",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Preferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferencia_general", models.TextField()),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cursos.curso"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.estudiante",
                    ),
                ),
            ],
        ),
    ]
