# Generated by Django 5.2.7 on 2025-10-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_curso_esta_activo_curso_fecha_creado_curso_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferencia",
            name="curso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cursos.curso",
            ),
        ),
    ]
